require(arules)

#######################################
#########deleted
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/10_00.txt", header=F, sep=",")
ud1<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud1), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/24_01.txt", header=F, sep=",")
ud2<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud2), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/168_0.txt", header=F, sep=",")
ud3<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud3), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/171_0.txt", header=F, sep=",")
ud4<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud4), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/317_0.txt", header=F, sep=",")
ud5<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud5), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/381_0.txt", header=F, sep=",")
ud6<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud6), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/849_1.txt", header=F, sep=",")
ud7<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud7), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/872_1.txt", header=F, sep=",")
ud8<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud8), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/892_1.txt", header=F, sep=",")
ud9<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud9), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/901_1.txt", header=F, sep=",")
ud10<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud10), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/1094_.txt", header=F, sep=",")
ud11<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud11), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/1175_.txt", header=F, sep=",")
ud12<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud12), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/1327_.txt", header=F, sep=",")
ud13<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud13), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/1921_.txt", header=F, sep=",")
ud14<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud14), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/1994_.txt", header=F, sep=",")
ud15<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud15), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/2060_.txt", header=F, sep=",")
ud16<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud16), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/2154_.txt", header=F, sep=",")
ud17<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud17), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/2661_.txt", header=F, sep=",")
ud18<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud18), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3022_.txt", header=F, sep=",")
ud19<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud19), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3031_.txt", header=F, sep=",")
ud20<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud20), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3094_.txt", header=F, sep=",")
ud21<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud21), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3165_.txt", header=F, sep=",")
ud22<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud22), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3282_.txt", header=F, sep=",")
ud23<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud23), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3288_.txt", header=F, sep=",")
ud24<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud24), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3369_.txt", header=F, sep=",")
ud25<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud25), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
d<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-deleted/3735_.txt", header=F, sep=",")
ud26<-unique(gsub("\\.[^\\.]*$","",unlist(d)))
write.table(as.list(ud26), file="D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")

if(FALSE){
td<-table(c(as.vector(ud1),as.vector(ud2),as.vector(ud3), 
as.vector(ud4),as.vector(ud5),as.vector(ud6),as.vector(ud7),as.vector(ud8)
,as.vector(ud9),as.vector(ud10),as.vector(ud11),as.vector(ud12),as.vector(ud13),as.vector(ud14)
,as.vector(ud15),as.vector(ud16),as.vector(ud17),as.vector(ud18),as.vector(ud19),as.vector(ud20)
,as.vector(ud21),as.vector(ud22),as.vector(ud23),as.vector(ud24),as.vector(ud25),as.vector(ud26)))
d<-head(sort(td, decreasing=TRUE),n=20)
par(las=2, mar=c(19,4,2,2),cex=0.8)
barplot(d, ylim=range(0,25))
title(ylab="Number of Applications", mgp=c(2,1,0))
title(xlab="Deleted API Calls Needs Permissions", mgp=c(15,1,0))
}
##########added
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/6_2AF.txt", header=F, sep=",")
ua1<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua1), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/97_12.txt", header=F, sep=",")
ua2<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua2), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/140_D.txt", header=F, sep=",")
ua3<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua3), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/168_4.txt", header=F, sep=",")
ua4<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua4), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/172_7.txt", header=F, sep=",")
ua5<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua5), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/326_A.txt", header=F, sep=",")
ua6<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua6), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/381_0.txt", header=F, sep=",")
ua7<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua7), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/547_0.txt", header=F, sep=",")
ua8<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua8), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/638_B.txt", header=F, sep=",")
ua9<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua9), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/849_0.txt", header=F, sep=",")
ua10<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua10), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/872_3.txt", header=F, sep=",")
ua11<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua11), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/896_A.txt", header=F, sep=",")
ua12<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua12), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/920_6.txt", header=F, sep=",")
ua13<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua13), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/967_0.txt", header=F, sep=",")
ua14<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua14), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/1094_.txt", header=F, sep=",")
ua15<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua15), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/1219_.txt", header=F, sep=",")
ua16<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua16), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/1327_.txt", header=F, sep=",")
ua17<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua17), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
#a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/1765_.txt", header=F, sep=",")
#ua18<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
#write.table(as.list(ua18), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/1922_.txt", header=F, sep=",")
ua19<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua19), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/1994_.txt", header=F, sep=",")
ua20<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua20), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/2004_.txt", header=F, sep=",")
ua21<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua21), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
#a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/2062_.txt", header=F, sep=",")
ua22<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua22), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/2154_.txt", header=F, sep=",")
ua23<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua23), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/2663_.txt", header=F, sep=",")
ua24<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua24), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/2685_.txt", header=F, sep=",")
ua25<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua25), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/2698_.txt", header=F, sep=",")
ua26<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua26), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3022_.txt", header=F, sep=",")
ua27<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua27), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3092_.txt", header=F, sep=",")
ua28<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua28), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3094_.txt", header=F, sep=",")
ua29<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua29), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
#a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3165_.txt", header=F, sep=",")
ua30<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua30), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3282_.txt", header=F, sep=",")
ua31<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua31), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3283_.txt", header=F, sep=",")
ua32<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua32), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3290_.txt", header=F, sep=",")
ua34<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua34), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3314_.txt", header=F, sep=",")
ua35<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua35), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3369_.txt", header=F, sep=",")
ua36<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua36), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")
a<-read.csv(file="D:/Ava/Empirical2018/TrojansResult/API-added/3735_.txt", header=F, sep=",")
ua37<-unique(gsub("\\.[^\\.]*$","",unlist(a)))
write.table(as.list(ua37), file="D:/Ava/Empirical2018/TrojansResult/API-added.csv", row.names=FALSE,col.names=FALSE,append=TRUE, sep=",")

if(FALSE){
ta<-table(c(as.vector(ua1),as.vector(ua2),as.vector(ua3), 
as.vector(ua4),as.vector(ua5),as.vector(ua6),as.vector(ua7),
as.vector(ua8), as.vector(ua9),as.vector(ua10),as.vector(ua11), 
as.vector(ua12),as.vector(ua13),as.vector(ua14),as.vector(ua15),as.vector(ua16),as.vector(ua17)
,as.vector(ua19),as.vector(ua20)
,as.vector(ua21),as.vector(ua22),as.vector(ua23),as.vector(ua24),as.vector(ua25)
,as.vector(ua26),as.vector(ua27),as.vector(ua28),as.vector(ua29),as.vector(ua30),as.vector(ua31)
,as.vector(ua32),as.vector(ua34),as.vector(ua35),as.vector(ua36),as.vector(ua37)))
a<-head(sort(ta, decreasing=TRUE),n=20)
par(las=2, mar=c(19,4,2,2),cex=0.8)
barplot(a, ylim=range(0,50))
title(ylab="Number of Applications", mgp=c(2,1,0))
title(xlab="Added API Calls", mgp=c(16.5,1,0))
}


TraceTrojanAdded <-read.transactions("D:/Ava/Empirical2018/TrojansResult/API-added.csv", sep=",")
TraceTrojanDeleted <-read.transactions("D:/Ava/Empirical2018/TrojansResult/API-deleted.csv", sep=",")


itemsets<-eclat(TraceTrojanAdded ,parameter=list(sup=0.05, minlen=1,maxlen=1))
itemsetsd<-eclat(TraceTrojanDeleted ,parameter=list(sup=0.05, minlen=1,maxlen=1))
itemsetsd<-setdiff(itemsetsd,itemsets)

#combine two itemsets; features
features<-c(itemsets,itemsetsd)

TrojanAddedTable <- is.subset(features,TraceTrojanAdded)
tTrojanAddedTable <-t(TrojanAddedTable)

TrojanDeletedTable <- is.subset(features,TraceTrojanDeleted)
tTrojanDeletedTable <-t(TrojanDeletedTable)

GGrow<-nrow(tTrojanAddedTable)+nrow(tTrojanDeletedTable)
C = matrix( ,nrow=GGrow, ncol=1)
colnames(C) <- c("Result")
for(i in 1:nrow(tTrojanAddedTable))
{
	C[i, ]<-1
}
for(i in nrow(tTrojanAddedTable)+1:nrow(tTrojanDeletedTable))
{
	C[i, ]<-0
}

tempa<-rbind(tTrojanAddedTable,tTrojanDeletedTable)
TracesTrojan<-cbind(tempa,C)

###############Use SMOTE to repeat
library(DMwR)
TracesTrojan<- as.data.frame( TracesTrojan)
TracesTrojan$Result <- as.factor(TracesTrojan$Result)
SMOTETracesTrojan <- SMOTE(Result ~ ., data=TracesTrojan, perc.over = 2000, perc.under=100)
prop.table(table(SMOTETracesTrojan$Result))


#save data
fTracesTrojan<-as.data.frame.matrix(TracesTrojan)
write.csv(fTracesTrojan, file = "D:/Ava/Empirical2018/TrojansResult/TracesTrojan.csv")
#> write.matrix(TracesTrojan, file = "D:/Ava/Empirical2018/TrojansResult/TracesTrojan1.csv", sep=",", row.names=TRUE)

